spring:
  profiles:
    active: dev
  application:
    name: peaktrack-server
  datasource:
    url: local_db_url
    username: local_db_username
    password: local_db_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    drop-first: false
    contexts: ${SPRING_PROFILES_ACTIVE:development}
server:
  port: 9090

security:
  jwt:
    secret-key: jwt_secret
    expiration-time:  ${JWT_EXPIRATION_TIME:3600000}