spring:
  application:
    name: peaktrack-server
  datasource:
    url: jdbc:mysql://localhost:3306/peaktrack-db?createDatabaseIfNotExist=true
    username: root
    password: MertMert96
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
server:
  port: 9090