spring:
  application:
    name: peaktrack-server
  datasource:
    url: jdbc:mysql://localhost:3306/peaktrack-db?createDatabaseIfNotExist=true
    username: root
    password: MertMert96
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    drop-first: false
    contexts: ${SPRING_PROFILES_ACTIVE:development}
server:
  port: 9090

security:
  jwt:
    secret-key: 4875ee092fb6821c8c69d4fe872c77b798046020bcdbc85d00d5d370f21e469d
    expiration-time: 3600000